
# Save path
model_save_dir: "./save_models"

# Load path
model_names: ["CNP", "NP", "ANP", "ANP_variational", "ANP_log_normal", "ANP_weibull"]
# model_path: [
#               "./save_models/CNP/test/model.pt"
#             ]
  
model_path: [
              "./save_models/CNP/test/model.pt",
              "./save_models/NP/test/model.pt", 
              "./save_models/ANP/test/model.pt",
              "./save_models/ANP_variational/test/model.pt", 
              "./save_models/ANP_log_normal/test/model.pt", 
              "./save_models/ANP_weibull/test/model.pt", 
            ]
